[project]
name = "deep-chemometrics"
version = "0.1.0"
description = ""
authors = [
    {name = "GDadda",email = "daniele.tanzilli@unimore.it"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch (>=2.7.1,<3.0.0)",
    "torchvision (>=0.22.1,<0.23.0)",
    "torchaudio (>=2.7.1,<3.0.0)",
    "numpy (>=2.3.1,<3.0.0)",
    "pandas (>=2.3.1,<3.0.0)",
    "matplotlib (>=3.10.3,<4.0.0)",
    "einops (>=0.8.1,<0.9.0)",
    "torcheval (>=0.0.7,<0.0.8)",
    "scipy (>=1.16.0,<2.0.0)",
    "scikit-learn (>=1.7.0,<2.0.0)",
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
